snowflake_super_store_sales:
  outputs:
    dev:
      type: snowflake
      account: "${SNOWFLAKE_ACCOUNT}"
      database: "${SNOWFLAKE_DATABASE}"
      password: "${SNOWFLAKE_PASSWORD}"
      role: "${SNOWFLAKE_ROLE}"
      schema: "${SNOWFLAKE_SCHEMA}"
      user: "${SNOWFLAKE_USER}"
      warehouse: "${SNOWFLAKE_WAREHOUSE}"
      threads: 4
  target: dev